name: spacing_generator
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  flutter:
    sdk: flutter
  source_gen: ^1.4.0
  spacing_generator_annotation:
    path: ../spacing_generator_annotation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
